from __future__ import annotations

import json
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _slug(value: str, fallback: str = "feature") -> str:
    """Create a stable filesystem-safe slug for Spec Kit feature folders."""
    cleaned = re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-")
    return cleaned[:72].strip("-") or fallback


def _text(value: Any) -> str:
    """Render strings and compact dict/list values into readable Markdown text."""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, dict):
        title = value.get("title") or value.get("name") or value.get("label") or value.get("state")
        details = value.get("description") or value.get("behavior") or value.get("rationale") or value.get("notes")
        if title and details:
            return f"{title}: {details}"
        if title:
            return str(title)
    return json.dumps(value, ensure_ascii=False)


def _bullets(values: list[Any], empty: str = "None specified.") -> list[str]:
    """Render a markdown bullet list from Layer 3 structured arrays."""
    items = [_text(item) for item in values if _text(item)]
    return [f"- {item}" for item in items] if items else [f"- {empty}"]


def _numbered(values: list[Any], prefix: str) -> list[str]:
    """Render numbered requirements with deterministic IDs."""
    items = [_text(item) for item in values if _text(item)]
    if not items:
        return ["- No explicit requirements supplied by this section."]
    return [f"- **{prefix}-{index:03d}**: {item}" for index, item in enumerate(items, start=1)]


def _lineage(project: Any, brief: dict[str, Any], layer2_graph: dict[str, Any], card: dict[str, Any]) -> dict[str, Any]:
    """Build the cross-layer provenance payload that follows a generated spec."""
    pillars = {item.get("id"): item for item in layer2_graph.get("pillars", [])}
    features = {item.get("id"): item for item in layer2_graph.get("features", [])}
    feature = features.get(card.get("feature_id"), {})
    pillar = pillars.get(card.get("parent_pillar_id"), {})
    return {
        "project": project.model_dump(mode="json") if hasattr(project, "model_dump") else project,
        "layer0": {
            "brief_id": brief.get("id"),
            "product_idea": brief.get("product_idea") or getattr(project, "idea", ""),
            "target_users": brief.get("target_users", ""),
            "goals": brief.get("goals", []),
            "constraints": brief.get("constraints", ""),
        },
        "layer1": {
            "pillar_id": card.get("parent_pillar_id"),
            "title": pillar.get("title") or card.get("parent_pillar_title"),
            "description": pillar.get("description", ""),
        },
        "layer2": {
            "feature_id": card.get("feature_id"),
            "canonical_name": feature.get("canonical_name") or card.get("feature_name"),
            "description": feature.get("description") or card.get("feature_description"),
            "status": feature.get("status"),
            "coverage_family": feature.get("coverage_family", ""),
            "candidate_source_ids": feature.get("candidate_source_ids", []),
        },
        "layer3": {
            "card_id": card.get("id"),
            "review_state": card.get("review_state"),
            "downstream_readiness_score": card.get("downstream_readiness_score"),
            "updated_at": card.get("updated_at"),
            "provenance": card.get("provenance", {}),
        },
    }


def _spec_markdown(card: dict[str, Any], lineage: dict[str, Any]) -> str:
    """Create a Spec Kit-ready requirements seed focused on what and why."""
    req_prefix = _slug(card.get("feature_name", "feature")).replace("-", "").upper()[:10] or "REQ"
    decisions = card.get("open_decisions", [])
    unresolved = [item for item in decisions if item.get("status") != "resolved"]
    resolved = [item for item in decisions if item.get("status") == "resolved"]
    relationships = card.get("relationships", [])
    coverage = (card.get("pressure_test") or {}).get("coverage_gap_analysis") or {}
    lines = [
        f"# Feature Specification: {card.get('feature_name', 'Untitled feature')}",
        "",
        "> Generated by Strata from an approved Layer 3 Capability Design Card. Use this as the input seed for `/speckit.specify`, then run `/speckit.clarify`, `/speckit.plan`, `/speckit.checklist`, `/speckit.tasks`, and `/speckit.analyze` inside the target repository.",
        "",
        "## Product Context",
        f"- Product idea: {lineage['layer0'].get('product_idea')}",
        f"- Layer 1 pillar: {lineage['layer1'].get('title')}",
        f"- Source Layer 2 capability: {lineage['layer2'].get('canonical_name')}",
        f"- Target users: {lineage['layer0'].get('target_users') or 'Not specified.'}",
        "",
        "## User Value And Purpose",
        card.get("product_purpose") or "No purpose captured.",
        "",
        "## Feature Archetype",
        card.get("feature_archetype") or "No archetype captured.",
        "",
        "## Functional Requirements",
        *_numbered(card.get("product_behaviors", []), req_prefix),
        "",
        "## Variants And Configuration",
        *_bullets(card.get("supported_variants", []), "No variants specified."),
        *_bullets(card.get("configurable_options", []), "No configurable options specified."),
        "",
        "## Validation And Constraints",
        *_numbered(card.get("validation_constraints", []), f"{req_prefix}-VAL"),
        "",
        "## Lifecycle States",
        *_bullets(card.get("lifecycle_states", []), "No lifecycle states specified."),
        "",
        "## Edge Cases",
        *_bullets(card.get("edge_cases", []), "No edge cases specified."),
        "",
        "## Dependencies, Overlaps, And Relationships",
        *_bullets(card.get("dependencies", []), "No dependencies specified."),
        *_bullets(card.get("overlaps_conflicts", []), "No overlaps or conflicts specified."),
        *([
            f"- {edge.get('relationship_type')} -> {edge.get('target_feature_id')}: {edge.get('rationale', '')}"
            for edge in relationships
        ] or ["- No relationship edges specified."]),
        "",
        "## Risks",
        *_bullets(card.get("product_risks", []), "No product risks specified."),
        "",
        "## Resolved Product Decisions",
        *([
            f"- {item.get('question')}: {item.get('resolution')}"
            for item in resolved
        ] or ["- No resolved decisions recorded."]),
        "",
        "## Open Questions",
        *([
            f"- {item.get('question')}"
            for item in unresolved
        ] or ["- None. Strata export gates require unresolved decisions to be resolved."]),
        "",
        "## Coverage Gap Notes",
        coverage.get("summary") or "No Layer 3 coverage-gap check has been attached.",
    ]
    return "\n".join(lines).strip() + "\n"


def _traceability_markdown(card: dict[str, Any], lineage: dict[str, Any]) -> str:
    """Create a compact traceability document from Layer 0 through Layer 3."""
    return "\n".join([
        f"# Traceability: {card.get('feature_name')}",
        "",
        f"- Layer 0 brief: {lineage['layer0'].get('brief_id')}",
        f"- Product idea: {lineage['layer0'].get('product_idea')}",
        f"- Layer 1 pillar: {lineage['layer1'].get('title')} ({lineage['layer1'].get('pillar_id')})",
        f"- Layer 2 capability: {lineage['layer2'].get('canonical_name')} ({lineage['layer2'].get('feature_id')})",
        f"- Layer 3 card: {lineage['layer3'].get('card_id')}",
        f"- Readiness: {lineage['layer3'].get('downstream_readiness_score')}",
        "",
        "## Handoff Rule",
        "Preserve this lineage when Spec Kit clarifies, plans, or decomposes the feature so implementation work remains tied to the approved Strata product definition.",
        "",
    ])


def _handoff_markdown(card_count: int) -> str:
    """Create user-facing instructions for using the generated bundle with Spec Kit."""
    return "\n".join([
        "# Strata To Spec Kit Handoff",
        "",
        f"This bundle contains {card_count} Spec Kit-ready implementation slice seed(s).",
        "",
        "## Recommended Flow",
        "1. Copy the `specs/` folders into the target repository, or paste a slice's `spec.md` into `/speckit.specify`.",
        "2. Do not overwrite an existing `.specify/memory/constitution.md`; compare Strata lineage against the target repo's constitution instead.",
        "3. Run `/speckit.clarify` for any product ambiguity that remains.",
        "4. Run `/speckit.plan` inside the target repo so architecture and stack decisions are grounded in that codebase.",
        "5. Run `/speckit.checklist`, `/speckit.tasks`, `/speckit.analyze`, and only then `/speckit.implement`.",
        "",
        "Strata intentionally exports product requirements and provenance, not implementation plans or coding tasks.",
        "",
    ])


def _readiness_blockers(card: dict[str, Any], feature_status: str | None) -> list[str]:
    """Return export blockers for one Layer 3 card."""
    blockers: list[str] = []
    if card.get("review_state") != "approved":
        blockers.append("Card must be approved.")
    if feature_status != "approved":
        blockers.append("Source Layer 2 feature must still be approved.")
    unresolved = [item for item in card.get("open_decisions", []) if item.get("status") != "resolved"]
    if unresolved:
        blockers.append("Resolve all Layer 3 open decisions before handoff.")
    if (card.get("pressure_test") or {}).get("stale"):
        blockers.append("Rerun the pressure test after recent edits.")
    return blockers


def spec_kit_handoff_preview(
    *,
    layer3_snapshot: dict[str, Any],
    feature_statuses: dict[str, str],
) -> dict[str, Any]:
    """Summarize which cards are safe to move into Spec Kit."""
    approved = [card for card in layer3_snapshot.get("cards", []) if card.get("review_state") == "approved"]
    rows = []
    for card in layer3_snapshot.get("cards", []):
        blockers = _readiness_blockers(card, feature_statuses.get(card.get("feature_id")))
        rows.append({
            "card_id": card.get("id"),
            "feature_name": card.get("feature_name"),
            "ready": not blockers,
            "blockers": blockers,
            "review_state": card.get("review_state"),
            "readiness_score": card.get("downstream_readiness_score"),
        })
    return {
        "approved_card_count": len(approved),
        "ready_card_count": sum(1 for row in rows if row["ready"]),
        "cards": rows,
    }


def export_spec_kit_handoff(
    *,
    project: Any,
    brief: dict[str, Any],
    layer2_graph: dict[str, Any],
    layer3_snapshot: dict[str, Any],
    feature_statuses: dict[str, str],
    exports_dir: Path,
    card_ids: list[str] | None = None,
) -> dict[str, Any]:
    """Write Spec Kit-ready files plus a zip archive and return local paths."""
    selected_ids = set(card_ids or [])
    selected_cards = [
        card for card in layer3_snapshot.get("cards", [])
        if (not selected_ids or card.get("id") in selected_ids)
    ]
    if not selected_cards:
        raise ValueError("Select at least one Layer 3 card for delivery handoff.")
    blockers = {
        card.get("id"): _readiness_blockers(card, feature_statuses.get(card.get("feature_id")))
        for card in selected_cards
    }
    blocked = {card_id: reasons for card_id, reasons in blockers.items() if reasons}
    if blocked:
        raise ValueError(f"Some selected cards are not ready for handoff: {blocked}")

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    base_slug = _slug(getattr(project, "name", "") or "strata-project", "strata-project")
    output_dir = exports_dir / f"{base_slug}-speckit-handoff-{timestamp}"
    specs_dir = output_dir / "specs"
    specs_dir.mkdir(parents=True, exist_ok=True)
    slices = []
    for index, card in enumerate(selected_cards, start=1):
        folder_name = f"{index:03d}-{_slug(card.get('feature_name', ''), f'feature-{index}')}"
        folder = specs_dir / folder_name
        folder.mkdir(parents=True, exist_ok=True)
        lineage = _lineage(project, brief, layer2_graph, card)
        files = {
            "spec.md": _spec_markdown(card, lineage),
            "traceability.md": _traceability_markdown(card, lineage),
            "strata-lineage.json": json.dumps(lineage, indent=2, ensure_ascii=False) + "\n",
        }
        for filename, content in files.items():
            (folder / filename).write_text(content, encoding="utf-8")
        slices.append({
            "card_id": card.get("id"),
            "feature_name": card.get("feature_name"),
            "folder": f"specs/{folder_name}",
            "files": [f"specs/{folder_name}/{name}" for name in files],
        })

    summary = {
        "artifact_type": "strata_speckit_handoff",
        "artifact_version": "1.0",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "project_id": getattr(project, "id", ""),
        "slice_count": len(slices),
        "slices": slices,
    }
    (output_dir / "handoff.md").write_text(_handoff_markdown(len(slices)), encoding="utf-8")
    (output_dir / "handoff-summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    zip_path = output_dir.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in output_dir.rglob("*"):
            if path.is_file():
                archive.write(path, path.relative_to(output_dir))
    return {
        "output_dir": str(output_dir),
        "zip_path": str(zip_path),
        "slice_count": len(slices),
        "slices": slices,
    }
